inherits = "onedark"

"ui.background" = { bg = "default" }
"ui.statusline" = { bg = "default" }
"ui.statusline.inactive" = { bg = "default" }
"ui.popup" = { bg = "default" }
"ui.window" = { bg = "default" }
"ui.help" = { bg = "default" }
